// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBtKKDBEU29Oj8RlaacCjhTOzbOrgoGUI',
    appId: '1:269103901704:web:7b6c4ef44ca2ff79fbb5bd',
    messagingSenderId: '269103901704',
    projectId: 'todo-app-6ab0b',
    authDomain: 'todo-app-6ab0b.firebaseapp.com',
    storageBucket: 'todo-app-6ab0b.appspot.com',
    measurementId: 'G-3FN2R1NSL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJhZxGpiLyW-uXlUyNKjyCE55tLdt5STM',
    appId: '1:269103901704:android:5d3339fd21df45edfbb5bd',
    messagingSenderId: '269103901704',
    projectId: 'todo-app-6ab0b',
    storageBucket: 'todo-app-6ab0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKcNuYISE4dgR-ieVhGZ6pQFFppqMYEj4',
    appId: '1:269103901704:ios:047c0f6a6e5d42cffbb5bd',
    messagingSenderId: '269103901704',
    projectId: 'todo-app-6ab0b',
    storageBucket: 'todo-app-6ab0b.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKcNuYISE4dgR-ieVhGZ6pQFFppqMYEj4',
    appId: '1:269103901704:ios:94d868f6899d8483fbb5bd',
    messagingSenderId: '269103901704',
    projectId: 'todo-app-6ab0b',
    storageBucket: 'todo-app-6ab0b.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
